# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('user_id_1', models.IntegerField()),
                ('username_1', models.CharField(max_length=50)),
                ('user_id_2', models.IntegerField()),
                ('username_2', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
    ]
