# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('user_1', models.IntegerField()),
                ('user_2', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user_id_1',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='user_id_2',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='username_1',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='username_2',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='messages',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='receiver_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='sender_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='example.ChatSession'),
        ),
    ]
